### ISSUE TITLE
some questions about dropout

### ISSUE THREAD

**Issue by fantasyzl** [parasdahal/deepnet#5]
Hi,
I first used a simple three-tier CNN structure without dropout. The accuracy rate was over 90%. However, after I used dropout, the accuracy rate dropped to 40%. Is there any problem with my data set or is it another problem?

thank you
I

**Comment by parasdahal** [comment]
Using regularization will slightly dip the accuracy, but it should not be that drastic. Please try different values of hyperparameters as it highly depends on your data to give a generic suggestion here.
